### PR TITLE
Overrides for 5.24.6

### PR DESCRIPTION
**Pull request by Edzelopez**

### CODE REVIEW

**Comment by seamuslee001** [comment]
@Edzelopez should this be merged now?

**Comment by Edzelopez** [comment]
Yes, I believe so. However, we should really look to removing some of the overrides using the hook introduced in 5.24.

**Comment by JoeMurray** [comment]
Edsel, could you work on removing these overrides this week and pass to @seamuslee001 for QA?

**Comment by JoeMurray** [comment]
> The CSS above is copied from core which was being overridden by some of DE's CSS. This will likely not be released as a general extension release.

Hmm. So this should not be committed to master but to a client branch, or perhaps even into a theming file in a custom ext for that client. Can you take that out from here.

Separately, can you review with Monish and Seamus what the best practice is for avoiding copy and paste in this context?

**Pull request merged**
